// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeCompanyIS.DataAccess.Postgres;

#nullable disable

namespace TradeCompanyIS.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(TradeCompanyDbContext))]
    partial class TradeCompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressDelivery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdCountry")
                        .HasColumnType("uuid");

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdCountry");

                    b.ToTable("ClientsTable");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.CountriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CountriesTable");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ItemsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdWareHouse")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("QuantityWareHouse")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdWareHouse");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ItemsTable");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.OrdersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateReg")
                        .HasColumnType("date");

                    b.Property<Guid>("IdClients")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdItem")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdClients");

                    b.HasIndex("IdItem");

                    b.ToTable("OredersTable");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ProvidersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdCountry")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCountry");

                    b.ToTable("ProvidersTable");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.SuppliesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdItem")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProvider")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdWarehouse")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdProvider");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("SuppliesTable");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.UsersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UsersTable");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.WareHousesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdCountry")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdCountry");

                    b.ToTable("WareHousesTable");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.CountriesEntity", "CountriesRef")
                        .WithMany("ClientsRef")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CountriesRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ItemsEntity", b =>
                {
                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.WareHousesEntity", "WareHouseRef")
                        .WithMany("ItemsRef")
                        .HasForeignKey("IdWareHouse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WareHouseRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.OrdersEntity", b =>
                {
                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.ClientsEntity", "ClientsRef")
                        .WithMany("OrdersRef")
                        .HasForeignKey("IdClients")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.ItemsEntity", "ItemsRef")
                        .WithMany("OrdersRef")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientsRef");

                    b.Navigation("ItemsRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ProvidersEntity", b =>
                {
                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.CountriesEntity", "CountriesRef")
                        .WithMany("ProvidersRef")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CountriesRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.SuppliesEntity", b =>
                {
                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.ItemsEntity", "ItemsRef")
                        .WithMany("SuppliesRef")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.ProvidersEntity", "ProvidersRef")
                        .WithMany("SuppliesRef")
                        .HasForeignKey("IdProvider")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.WareHousesEntity", "WareHousesRef")
                        .WithMany("SuppliesRef")
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemsRef");

                    b.Navigation("ProvidersRef");

                    b.Navigation("WareHousesRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.WareHousesEntity", b =>
                {
                    b.HasOne("TradeCompanyIS.DataAccess.Postgres.Models.CountriesEntity", "CountriesRef")
                        .WithMany("WareHousesRef")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CountriesRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.Navigation("OrdersRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.CountriesEntity", b =>
                {
                    b.Navigation("ClientsRef");

                    b.Navigation("ProvidersRef");

                    b.Navigation("WareHousesRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ItemsEntity", b =>
                {
                    b.Navigation("OrdersRef");

                    b.Navigation("SuppliesRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.ProvidersEntity", b =>
                {
                    b.Navigation("SuppliesRef");
                });

            modelBuilder.Entity("TradeCompanyIS.DataAccess.Postgres.Models.WareHousesEntity", b =>
                {
                    b.Navigation("ItemsRef");

                    b.Navigation("SuppliesRef");
                });
#pragma warning restore 612, 618
        }
    }
}
